{{ if or .Values.secrets .Values.b64secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dotnet-app.fullname" . }}
  labels:
    {{- include "dotnet-app.labels" . | nindent 4 }}
type: Opaque
{{- if .Values.secrets }}
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- if .Values.b64secrets }}
data:
  {{- range $key, $value := .Values.b64secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
---
{{- end }}
